### ISSUE TITLE
Busca limitada a categoria "Seriados"

### ISSUE THREAD

**Issue by Nickneo3** [gabrielbdsantos/BJ_Sickrage#1]
Olá, percebi que na string de busca executada pelo BJ_Sickrage é montada a URL https://bj-share.me/torrents.php?searchstr=power+couple+brasil&filter_cat%5B2%5D=1&order_by=seeders&order_way=desc

com o filter_cat está definido, ele está buscando apenas na categoria "seriados", o que seria ok se nao fosse a categoria "Videos de TV" também ter seriados (notadamente os nacionais) o que é o caso deste que aí está, seria o caso de modificar apenas as categorias.

Abraços e obrigado

**Comment by gabrielbdsantos** [comment]
A simples mudança da url de busca não resolveria o problema. O modo como o BJ apresenta os resultados de novelas e seriados nacionais é totalmente diferente do modo em que seriados internacionais são apresentados.

Seria necessária uma implementação que identificasse ambos os casos. Já foi solicitado isso e, assim que tiver tempo, pretendo implementar algo.
