### ISSUE TITLE
Mais dados no release name.

### ISSUE THREAD

**Issue by alangregory** [gabrielbdsantos/BJ_Sickrage#2]
Qual a possibilidade de adicionar mais dados ao nome da release para filtros.
Exemplo: Dual Áudio

**Comment by gabrielbdsantos** [comment]
Com qual finalidade?
Lembrando que o SickRage não possui filtros para dicernir entre dublado/legendado/dual áudio.

**Comment by alangregory** [comment]
Desculpa Gabriel, repositório errado, era pra ser no do couch, estava com os 2 abertos.
