### ISSUE TITLE
Erro de SSL

### ISSUE THREAD

**Issue by marcio-ota** [gabrielbdsantos/BJ_Sickrage#3]
Não esta mais sendo possível fazer pesquisas, ocorre um erro de SSL.
Pode ser algum problema no certificado do BJ-Share.

[BJ-Share] :: Request failed: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

[BJ-Share] :: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickRage/sickbeard/helpers.py", line 1511, in handle_requests_exception
    raise requests_exception
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

[BJ-Share] :: Unable to connect to provider

[BJ-Share] :: Transaction with 12 queries executed

**Comment by gabrielbdsantos** [comment]
Tive esse problema no passado, mas foi algo referente ao BJ. Nem pelo navegador conseguia acessar. Depois de algumas horas, voltou ao normal.

Se o problema ainda persiste, informe a versão do SickRage, do BJ-Plugin e seu OS para investigarmos melhor.
